FROM tutum/lamp
MAINTAINER PAAS EMAIL <sidnei.weber@gmail.com>

RUN apt-get update
RUN apt-get install -y phpmyadmin
#RUN echo "AddType application/x-httpd-php .php" > /etc/apache2/mods-enabled/mime.conf
